lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    resources "/users", UserController
    resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker_web/templates/page/index.html.eex
<div class="row">
  <div class="col">
    <h1>TASK TRACKER</h1><br>
    <h2>Log In</h2><br>
   <!-- session_path(@conn, :create) -->
   <%= form_tag("/session", method: :post) do %>
     <div class="form-group">
       Email
       <input type="email" name="email" placeholder="user@example.com" >
     </div>
     <br>
     <!-- passwords come later -->
     <div class="form-group">
       <button class="btn btn-primary">Log in</button>
       <%= link "Register", to: user_path(@conn, :new) %>
     </div>
   <% end %>
  </div>
</div>