lib/tasktracker_web/router.ex
defmodule TasktrackerWeb.Router do
  use TasktrackerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :get_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  def get_current_user(conn, _params) do
    # TODO: Move this function out of the router module.
    user_id = get_session(conn, :user_id)
    user = Tasktracker.Accounts.get_user(user_id || -1)
    assign(conn, :current_user, user)
  end

  scope "/", TasktrackerWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/feed", PageController, :feed
    resources "/users", UserController
    resources "/tasks", TaskController
    post "/session", SessionController, :create
    delete "/session", SessionController, :delete
  end

  # Other scopes may use custom stacks.
  # scope "/api", TasktrackerWeb do
  #   pipe_through :api
  # end
end

lib/tasktracker/accounts/user.ex
defmodule Tasktracker.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Tasktracker.Accounts.User

  schema "users" do
    field :email, :string
    field :name, :string
    has_many :task, Tasktracker.Tracker.Task, on_delete: :nilify_all, foreign_key: :user_id
    has_many :assigned_task, Tasktracker.Tracker.Task, on_delete: :nilify_all, foreign_key: :assigned_to
    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:email, :name])
    |> validate_required([:email, :name])
    |> unique_constraint(:email)
  end
end

lib/tasktracker_web/controllers/user_controller.ex
defmodule TasktrackerWeb.UserController do
  use TasktrackerWeb, :controller

  alias Tasktracker.Accounts
  alias Tasktracker.Accounts.User

  def index(conn, _params) do
    users = Accounts.list_users()
    render(conn, "index.html", users: users)
  end

  def new(conn, _params) do
    changeset = Accounts.change_user(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
      case Accounts.create_user(user_params) do
        {:ok, user} ->
          conn
          |> put_flash(:info, "User created successfully.")
          |> redirect(to: page_path(conn, :index))
        {:error, %Ecto.Changeset{} = changeset} ->
          render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    render(conn, "show.html", user: user)
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    changeset = Accounts.change_user(user)
    render(conn, "edit.html", user: user, changeset: changeset)
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

lib/tasktracker_web/views/user_view.ex
defmodule TasktrackerWeb.UserView do
  use TasktrackerWeb, :view
end

lib/tasktracker_web/templates/user/edit.html.eex
<h2>Edit Details</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<%= if @current_user.email=="admin@gmail.com" do %>
<span><%= link "Back", to: user_path(@conn, :index) %></span>
<% else %>
<span><%= link "Back", to: user_path(@conn, :show, @current_user) %></span>
<% end %>

lib/tasktracker_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control", type: "email", placeholder: "user@example.com" %>
    <span class="error"> <%= error_tag f, :email %> </span>
  </div>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <span class="error"> <%= error_tag f, :name %> </span>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tasktracker_web/templates/user/index.html.eex
<%= if !(@current_user==nil) and  @current_user.email=="admin@gmail.com" do %>
<h2>Listing Users</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>User ID</th>
      <th>Email</th>
      <th>Name</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for user <- @users do %>
    <tr>
      <td><%= user.id %></td>
      <td><%= user.email %></td>
      <td><%= user.name %></td>

      <td class="text-right">
        <span><%= link "Delete", to: user_path(@conn, :delete, user), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "Back", to: task_path(@conn, :index) %></span>
<% else %>
<span>Admin Login required</span><br><br>
<span><%= button "Login", to: page_path(@conn, :index), method: "get", class: "btn btn-primary" %></span>
<% end %>

lib/tasktracker_web/templates/user/new.html.eex
<h2>New User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

<span><%= link "Back", to: page_path(@conn, :index) %></span>

lib/tasktracker_web/templates/user/show.html.eex
<h2>Account Details</h2><br>

<ul>

  <li>
    <strong>UserID:</strong>
    <%= @user.id %>
  </li>

  <br>

  <li>
    <strong>Email:</strong>
    <%= @user.email %>
  </li>

  <br>

  <li>
    <strong>Name:</strong>
    <%= @user.name %>
  </li>

</ul>

<br>
<span><%= button "Edit", to: user_path(@conn, :edit, @user), method: "get", class: "btn btn-primary" %></span>
<span><%= link "Back", to: task_path(@conn, :index) %></span>